{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tcp-drain.serviceAccountName" . }}
  labels:
{{ include "tcp-drain.labels" . | indent 4 }}
{{- end -}}
